### ISSUE TITLE
Error configuration log

### ISSUE THREAD

**Issue by wifi75** [maxill1/addons#1]
hello after HA update the component not work  see my log:
```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:54:25] INFO: Passing /data/options.json to ialarm-mqtt@ version with node-ialarm@ 0.4.4
Found arg --hassos with value /data/options.json
Trying to merge HASSOS options file (/data/options.json) with default config.json
Config.json value not specified on /data/options.json using default 'ialarm/alarm/configStatus' on ["topics","alarm","configStatus"]
Config.json value not specified on /data/options.json using default 'ialarm/sensors/zone_${zoneId}' on ["topics","sensors","zone","state"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/battery/config' on ["hadiscovery","topics","sensorBatteryConfig"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/alarm/config' on ["hadiscovery","topics","sensorAlarmConfig"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/binary_sensor/ialarm_zone_${zoneId}/connectivity/config' on ["hadiscovery","topics","sensorConnectivityConfig"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/switch/ialarm/clear_cache/config' on ["hadiscovery","topics","clearCacheConfig"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/switch/ialarm/clear_discovery/config' on ["hadiscovery","topics","clearDiscoveryConfig"]
Config.json value not specified on /data/options.json using default '${discoveryPrefix}/switch/ialarm/clear_triggered/config' on ["hadiscovery","topics","clearTriggeredConfig"]
Starting up...
Status polling every  30000  ms
Events polling every  10000  ms
Loading zone cache...
Connected to 192.168.1.81:80
Disconnecting from 192.168.1.81:80
error [object Object]
{ event: '',
  error:
   { Error: Text data outside of root node.
   Line: 0
   Column: 81
   Char: {
       at error (/app/node_modules/sax/lib/sax.js:651:10)
       at strictFail (/app/node_modules/sax/lib/sax.js:677:7)
       at SAXParser.write (/app/node_modules/sax/lib/sax.js:1035:15)
       at Object.module.exports [as xml2js] (/app/node_modules/xml-js/lib/xml2js.js:346:12)
       at Promise (/app/node_modules/ialarm/src/meian-socket.js:120:42)
       at new Promise (<anonymous>)
       at _receive (/app/node_modules/ialarm/src/meian-socket.js:107:20)
       at Socket.<anonymous> (/app/node_modules/ialarm/src/meian-socket.js:238:17)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12) note: [Circular] } }
ialarm/alarm/error - error publishing...not connected
Connection closed
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by wifi75** [comment]
Sorry port it is now 18034...


now it is ok!

**Comment by maxill1** [comment]
no problem! :+1:
