### ISSUE TITLE
SyntaxError: Unexpected token after updating to versoin 2.0.8

### ISSUE THREAD

**Issue by maurizioandreotti60** [maxill1/addons#2]
I have just updated iAlarm to version 2.0.8 but now the startup produce the following error:

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:54:48] INFO: Passing /data/options.json to ialarm-mqtt@ 0.11.0 with node-ialarm@ 0.6.0
/app/ialarm-mqtt/bin/ialarm-mqtt.js:2
import { ialarmMqtt } from '../index.js'
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

My HA installation is HAOS at release 2022.11.2

**Comment by maxill1** [comment]
should be fixed, upgrade to 2.0.8bis

https://github.com/maxill1/ialarm-mqtt/issues/36
